### ISSUE TITLE
503 Errors

### ISSUE THREAD

**Issue by mvicari** [jadolg/porkbun-ddns#11]
Running in docker. 

`level=error msg="status: 503 message: <html>\r\n<head><title>503 Service Temporarily Unavailable</title></head>\r\n<body>\r\n<center><h1>503 Service Temporarily Unavailable</h1></center>\r\n<hr><center>openresty</center>\r\n</body>\r\n</html>\r\n"`

config.yaml looks like this (modified to hide details):
```
update_interval_minutes: 10

credentials:
  n:
    porkbun_api_key: pk1_...
    porkbun_secret_key: sk1_...

records:
  - domain: x.com
    host: A
    ipv4: true
    credentials: n
  - domain: x.com
    host: B
    ipv4: true
    credentials: n
  - domain: x.com
    host: C
    ipv4: true
    credentials: n
  - domain: x.com
    host: D
    ipv4: true
    credentials: n
  - domain: x.com
    host: E
    ipv4: true
    credentials: n
  - domain: x.com
    host: F
    ipv4: true
    credentials: n
```
